name: Manifest Check
on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch PR Author
        id: pr-author
        run: |
          AUTHOR=$(gh pr view $PR_NUMBER --json author --jq '.author.login' --repo $REPO)
          echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Validate Manifest
        run: |
          python .github/plugins/validate_manifest.py "projects/${{ github.event.pull_request.head.ref }}/manifest.json" "${{ env.AUTHOR }}"
  
  update:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Registry
        run: |
          python .github/plugins/update_registry.py
          git config --global user.name "GitHub Bot"
          git config --global user.email "actions@github.com"
          git add projects/_registry.json
          git commit -m "[CLI] Update registry for ${{ github.event.pull_request.head.ref }}"
          git push

  validate-PR-privileges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Team Membership
        id: check-admin
        uses: actions/github-script@v6
        with:
          script: |
            const { data: members } = await github.rest.teams.listMembersInOrg({
              org: context.repo.owner,
              team_slug: 'admins',  # Replace with your actual team slug
            });
            const isAdmin = members.some(member => member.login === context.actor);
            core.setOutput('is-admin', isAdmin);
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Admin Bypass
        id: bypass
        run: |
          if [ "${{ steps.check-admin.outputs.is-admin }}" == "true" ]; then
            echo "Admin user detected - bypassing validation"
            echo "SKIP_VALIDATION=true" >> $GITHUB_ENV
          else
            echo "Proceeding with validation"
          fi

      - name: Validate PR
        if: env.SKIP_VALIDATION != 'true'
        run: |
          python .github/plugins/validate_PR.py --author "${{ github.actor }}"