name: Manifest Check
on:
  push:
    paths:
      - 'projects/**'
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Commit Author
        id: commit-author
        run: |
          echo "The github.ref_name is: ${{ github.ref_name }}"
          AUTHOR="${GITHUB_ACTOR}"  # Directly use the actor for a push event
          echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV
      
      - name: Determine Affected Project
        id: affected-project
        run: |
          # Find the modified project directories
          MODIFIED_DIRS=$(git diff --name-only $GITHUB_SHA^ $GITHUB_SHA | grep '^projects/' | sed 's|/.*||' | uniq)
          if [ -z "$MODIFIED_DIRS" ]; then
            echo "No projects affected."
            exit 1
          fi
          # Join the modified directories to a variable (you can adapt this logic as needed)
          PROJECTS=$(echo "$MODIFIED_DIRS" | tr '\n' ' ')
          echo "AFFECTED_PROJECTS=$PROJECTS" >> $GITHUB_ENV
          echo "Affected projects: $PROJECTS"

      - name: Validate Manifests
        run: |
          for PROJECT in ${{ env.AFFECTED_PROJECTS }}; do
              python .github/plugins/validate_manifest.py "projects/$PROJECT/manifest.json" "${{ env.AUTHOR }}"
          done

  update:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Registry
        run: |
          python .github/plugins/update_registry.py
          git config --global user.name "GitHub Bot"
          git config --global user.email "actions@github.com"
          git add projects/_registry.json
          git commit -m "[CLI] Update registry for ${{ env.AFFECTED_PROJECTS }}"  # Reference the branch/tag here
          git push

  validate-push-privileges:
    needs: update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Team Membership
        id: check-admin
        uses: actions/github-script@v6
        with:
          script: |
            const { data: members } = await github.rest.teams.listMembersInOrg({
              org: context.repo.owner,
              team_slug: 'admins',  # Replace with your actual team slug
            });
            const isAdmin = members.some(member => member.login === context.actor);
            core.setOutput('is-admin', isAdmin);
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Admin Bypass
        id: bypass
        run: |
          if [ "${{ steps.check-admin.outputs.is-admin }}" == "true" ]; then
            echo "Admin user detected - bypassing validation"
            echo "SKIP_VALIDATION=true" >> $GITHUB_ENV
          else
            echo "Proceeding with validation"
          fi

      - name: Validate Push
        if: env.SKIP_VALIDATION != 'true'
        run: |
          python .github/plugins/validate_push.py "${{ github.actor }}"  # Use a different validation script if needed
