name: On Project Add
on:
  pull_request:
    branches: [main]
    paths: ["projects/**"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Manifest
        run: |
          python .github/plugins/validate_manifest.py "projects/${{ github.event.pull_request.head.ref }}/manifest.json"
  
  update:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Registry
        run: |
          python .github/plugins/update_registry.py
          git config --global user.name "GitHub Bot"
          git config --global user.email "actions@github.com"
          git add projects/_registry.json
          git commit -m "Update registry for ${{ github.event.pull_request.head.ref }}"
          git push